### PR TITLE
multiple validations and singletons

### LINKED ISSUE #2194: Singleton Configs act funny with commas
Thanks for creating an issue! Please fill out this form so we can be sure to have all the information we need, and to minimize back and forth.

* **What are we trying to do?**
Parse singleton values (integers, URLS, etc) in configs.

* **What feature or behavior is this required for?**
Budget bar, archive days (upcoming), URL handling, few other single-word configs.

* **How could we solve this issue? (Not knowing is okay!)**

Even though the help text says to enter numbers without commas, if you do enter a comma (i.e. budget bar max = `10,000`), it seems like that's being interpreted as a list (so budget bar max = `[10, 0]`). This *is* the expected behavior given the current code, so it's not really a bug, but it may make sense to add validation for singleton values versus things that _could be_ a list.

This also applies to URLs, start of week, hide practical support, etc... if you enter `https://cats,dogs.com` as a URL, it will _successfully validate_ and turn into `https://dogs.com` because the URL handling code calls `options.last`. I would argue that, given that input, we should fail to validate, rather than succeed in the way we are. (I could see this happening in practice with a minor typo: `sub.domain.com => sub,domain.com => domain.com`)
 
* **Anything else?**

I know this could make things more complicated because it will bifurcate our config handling. So may not be a priority issue; just came across it while adding new config fields.

### PR DESCRIPTION
**Pull request by elimbaum**
I rule and have completed some work on Case Manager that's ready for review!

This PR extends the config validation system to allow multiple validators per field. It also validates that singleton values aren't lists.

This pull request makes the following changes:
* Adds a new `validate_singleton` validator
* Turns validators from single functions to lists of functions
* Adds a few tests (let me know if we should test every field, rather than just a few)

(If there are changes to the views, please include a screenshot so we know what to look for!)

It relates to the following issue #s: 
* Fixes #2194 

For reviewer:
* Adjust the title to explain what it does for the notification email to the listserv.
* Tag this PR:
  * `feature` if it contains a feature, fix, or similar. This is anything that contains a user-facing fix in some way, such as frontend changes, alterations to backend behavior, or bug fixes.
  * `dependencies` if it contains library upgrades or similar. This is anything that upgrades any dependency, such as a Gemfile update or npm package upgrade.
* If it contains neither, no need to tag this PR.

### CODE REVIEW

File: app/models/config.rb [hunk 1]
```diff
@@ -134,15 +144,15 @@ def clean_config_value
...
 
       # no clean function, return
-      return if cleaner.nil?
+      return if cleaners.blank?
 
       # we need to use `method` because `cleaner` is a symbol... this converts
       # the symbol into a Method object, which we can then `call`...
       # See https://ruby-doc.org/core/Object.html#method-i-method
-      method(cleaner).call
+      cleaners.map { |cleaner| method(cleaner).call }
```
Comment (colinxfleming) [inline app/models/config.rb:155]: Pretty minor thing here - generally when I see `map` a reader (for example, me!) is expecting to see some values manipulated and returned. I think in this case the methods are all doing mutation rather than returning values, right? So we can use `each`, which will signal to the reader we don't really care what the return value is, and the interesting stuff is happening via mutation.

File: test/models/config_test.rb [hunk 2]
```diff
@@ -41,6 +41,25 @@ class ConfigTest < ActiveSupport::TestCase
       assert @bad_config.errors.messages[:config_key].include? "can't be blank"
     end
 
+    it 'should reject lists for singleton values' do
```
Comment (colinxfleming) [inline test/models/config_test.rb:44]: 👨‍🍳

**Review by colinxfleming — APPROVED** [review]
This PR is a lot of your thoughtful work paying off really beautiflully. Love this approach. and how smooth it is! One minor signal-to-other-writers suggestion in here around use of map over each, and then I think we can get this out. Outstanding work.

File: test/models/config_test.rb (hunk 2 above)
Comment (elimbaum) [reply test/models/config_test.rb:44]: are you ok with how this is structured (i.e. test of the functionality itself but not actually checking that all the fields validate in that way)? or flip it around?

File: app/models/config.rb (hunk 1 above)
Comment (elimbaum) [reply app/models/config.rb:155]: oops derp yes

File: test/models/config_test.rb (hunk 2 above)
Comment (colinxfleming) [reply test/models/config_test.rb:44]: nah I think this is a good test - taking a pair of representative examples is I think a good enough proveit here.
